author: Alexzvn
name: AuthmeLauncher
main: dev.alexzvn.authentication.AuthmeLauncher
descriptions: A none
website: github.com/alexzvn
api-version: 1.16

author: Alexzvn
descriptions: Extension allow auto authenticate between Minecraft server and custom launcher
version: 0.0.1

depend: [AuthMeReloaded]
